// <auto-generated />
using System;
using AlgoMe.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AlgoMe.Migrations
{
    [DbContext(typeof(AlgoMeContext))]
    partial class AlgoMeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AlgoMe.Models.Parameter", b =>
                {
                    b.Property<long>("ParameterId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<long>("Price");

                    b.Property<long?>("RequestId");

                    b.Property<long>("Weight");

                    b.HasKey("ParameterId");

                    b.HasIndex("RequestId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("AlgoMe.Models.Request", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Answer");

                    b.Property<long>("Capacity");

                    b.Property<int[]>("FullAnswer");

                    b.Property<string>("Name");

                    b.Property<int>("Percentage");

                    b.Property<double>("ProcessTime");

                    b.Property<bool>("Status");

                    b.HasKey("RequestId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("AlgoMe.Models.Parameter", b =>
                {
                    b.HasOne("AlgoMe.Models.Request", "Request")
                        .WithMany("Parameters")
                        .HasForeignKey("RequestId");
                });
#pragma warning restore 612, 618
        }
    }
}
